## Hands-On Data Preprocessing in Python
Learn how to effectively prepare data for successful data analytics
    
    AUTHOR: Dr. Roy Jafari 

### Chapter 4: Databases

In [1]:
import sqlite3
import pandas as pd

In [4]:
Connection = sqlite3.connect('chinook.db')
query_txt = "SELECT * FROM customers;"

df_customers = pd.read_sql_query(query_txt,Connection)
df_customers.head()

,CustomerId,FirstName,LastName,Company,Address,City,State,Country,PostalCode,Phone,Fax,Email,SupportRepId
0,1,Luís,Gonçalves,Embraer - Empresa Brasileira de Aeronáutica S.A.,"Av. Brigadeiro Faria Lima, 2170",São José dos Campos,SP,Brazil,12227-000,+55 (12) 3923-5555,+55 (12) 3923-5566,luisg@embraer.com.br,3
1,2,Leonie,Köhler,None,Theodor-Heuss-Straße 34,Stuttgart,None,Germany,70174,+49 0711 2842222,None,leonekohler@surfeu.de,5
2,3,François,Tremblay,None,1498 rue Bélanger,Montréal,QC,Canada,H2G 1A7,+1 (514) 721-4711,None,ftremblay@gmail.com,3
3,4,Bjørn,Hansen,None,Ullevålsveien 14,Oslo,None,Norway,0171,+47 22 44 22 22,None,bjorn.hansen@yahoo.no,4
4,5,František,Wichterlová,JetBrains s.r.o.,Klanova 9/506,Prague,None,Czech Republic,14700,+420 2 4172 5555,+420 2 4172 5555,frantisekw@jetbrains.com,4

In [37]:
import requests

stk_ticker = 'AMZN'
data_resolution = 'W'
timestamp_from = 1577865600
timestamp_to = 1609315200
API_Key = 'cp2miihr01qtd8fspo70cp2miihr01qtd8fspo7g'
Address_template = 'https://finnhub.io/api/v1/stock/candle?symbol={}&resolution={}&from={}&to={}&token={}';
Address_template = 'https://finnhub.io/api/v1/stock/quote?symbol={}&token={}';
# Address_template = 'https://finnhub.io/api/v1/stock/quote?symbol=AAPL';

# API_address = Address_template.format(stk_ticker,data_resolution,
#                                       timestamp_from,timestamp_to,API_Key)
API_address = Address_template.format(stk_ticker,API_Key)
r = requests.get(API_address)
print(r)

<Response [200]>

In [38]:
print(API_address)

https://finnhub.io/api/v1/stock/quote?symbol=AMZN&token=cp2miihr01qtd8fspo70cp2miihr01qtd8fspo7g

In [36]:
#https://pypi.org/project/websocket_client/
import websocket

def on_message(ws, message):
    print(message)

def on_error(ws, error):
    print(error)

def on_close(ws):
    print("### closed ###")

def on_open(ws):
    ws.send('{"type":"subscribe","symbol":"AAPL"}')
    ws.send('{"type":"subscribe","symbol":"AMZN"}')
    ws.send('{"type":"subscribe","symbol":"BINANCE:BTCUSDT"}')
    ws.send('{"type":"subscribe","symbol":"IC MARKETS:1"}')

if __name__ == "__main__":
    websocket.enableTrace(True)
    ws = websocket.WebSocketApp("wss://ws.finnhub.io?token=cp2miihr01qtd8fspo70cp2miihr01qtd8fspo7g",
                              on_message = on_message,
                              on_error = on_error,
                              on_close = on_close)
    ws.on_open = on_open
    ws.run_forever()

--- request header ---
GET /?token=cp2miihr01qtd8fspo70cp2miihr01qtd8fspo7g HTTP/1.1
Upgrade: websocket
Host: ws.finnhub.io
Origin: http://ws.finnhub.io
Sec-WebSocket-Key: lUy3qDr76myldgZbKalIUw==
Sec-WebSocket-Version: 13
Connection: Upgrade


-----------------------
--- response header ---
HTTP/1.1 101 Switching Protocols
Date: Thu, 16 May 2024 02:22:31 GMT
Connection: upgrade
Upgrade: websocket
Sec-WebSocket-Accept: Hs9eQE7mWYb3rlPkKkjfnTgmRdw=
CF-Cache-Status: DYNAMIC
Report-To: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v4?s=v8lG6mqGKE97NpV3L7nLBMlwMVToT7tZuGEv%2BZamvbqc4kZ161nFlssvfTdMpWEm4L8w2EONBVx6fGESBPbZCgQitir6jt%2BSeyAoJGA4afDf8zAQVzADrPsu8HSYn7UvnmkconHhcFuGCy0b"}],"group":"cf-nel","max_age":604800}
NEL: {"success_fraction":0,"report_to":"cf-nel","max_age":604800}
Server: cloudflare
CF-RAY: 8847e688290521a6-HKG
alt-svc: h3=":443"; ma=86400
-----------------------
send: b'\x81\xa4<\xe3\xc8\xe0G\xc1\xbc\x99L\x86\xea\xda\x1e\x90\xbd\x82O\x80\xba\x89^\x86\xea\xcc\x1e\x90\xb1\x8d^\x8c\xa4\xc2\x06\xc1\x89\xa1l\xaf\xea\x9d'
send: b'\x81\xa4\xd5\x0b\xf1\xb1\xae)\x85\xc8\xa5n\xd3\x8b\xf7x\x84\xd3\xa6h\x83\xd8\xb7n\xd3\x9d\xf7x\x88\xdc\xb7d\x9d\x93\xef)\xb0\xfc\x8fE\xd3\xcc'
send: b'\x81\xaf\x8d@6\x1f\xf6bBf\xfd%\x14%\xaf3C}\xfe#Dv\xef%\x143\xaf3Or\xef/Z=\xb7btV\xc3\x01x\\\xc8ztK\xce\x15e[\xd9bK'
send: b'\x81\xacc\x7f5\xef\x18]A\x96\x13\x1a\x17\xd5A\x0c@\x8d\x10\x1cG\x86\x01\x1a\x17\xc3A\x0cL\x82\x01\x10Y\xcdY]|\xacC2t\xbd(:a\xbcYN\x17\x92'

{"data":[{"c":null,"p":1.08837,"s":"IC MARKETS:1","t":1715826150285,"v":0},{"c":null,"p":66020,"s":"BINANCE:BTCUSDT","t":1715826151911,"v":0.00158},{"c":null,"p":66020.01,"s":"BINANCE:BTCUSDT","t":1715826152510,"v":0.00341},{"c":null,"p":66020,"s":"BINANCE:BTCUSDT","t":1715826152749,"v":0.017}],"type":"trade"}
{"data":[{"c":null,"p":1.08838,"s":"IC MARKETS:1","t":1715826151483,"v":0},{"c":null,"p":1.08837,"s":"IC MARKETS:1","t":1715826151743,"v":0},{"c":null,"p":66020,"s":"BINANCE:BTCUSDT","t":1715826153001,"v":0.03082},{"c":null,"p":66020.01,"s":"BINANCE:BTCUSDT","t":1715826153094,"v":0.01354}],"type":"trade"}

send: b'\x88\x82\xe1\xb3\xe4\xea\xe2['

### closed ###

In [39]:
print(r.json())

JSONDecodeError: Expecting value: line 1 column 1 (char 0)

In [6]:
AMZN_df = pd.DataFrame(r.json())
AMZN_df

          c          h          l          o   s           t         v
0   1891.97  1913.8900  1860.0000  1875.0000  ok  1577923200  19514188
1   1862.02  1917.8200  1855.0900  1909.8900  ok  1578528000  15160738
2   1887.46  1902.5000  1857.2500  1882.9900  ok  1579132800  13580875
3   1858.00  1894.9900  1815.3400  1885.1100  ok  1579737600  14688733
4   2039.87  2071.0200  1850.6100  1858.0000  ok  1580342400  37459327
5   2160.00  2185.9500  2024.8001  2041.0200  ok  1580947200  22414811
6   2170.22  2185.1000  2124.1050  2144.9900  ok  1581552000  11150195
7   1979.59  2176.7900  1958.4200  2173.0700  ok  1582156800  25788575
8   1975.83  1996.3300  1811.1290  1934.3800  ok  1582761600  36706851
9   1820.86  1960.7200  1761.2901  1933.0000  ok  1583366400  30615163
10  1830.00  1857.7750  1626.0318  1721.9800  ok  1583971200  49635551
11  1885.84  1957.0000  1812.0000  1860.0000  ok  1584576000  41652435
12  1907.70  1993.0200  1889.2900  1902.0000  ok  1585180800  26994603
13  2043.00  2044.0000  1889.1500  1901.6400  ok  1585785600  22810332
14  2307.68  2333.3690  2017.6600  2044.3000  ok  1586390400  26326086
15  2363.49  2460.9981  2279.6600  2346.0000  ok  1586995200  37433879
16  2372.71  2444.8800  2306.0000  2399.9800  ok  1587600000  24405033
17  2351.26  2475.0000  2256.3800  2419.8400  ok  1588204800  30533452
18  2367.92  2419.6650  2337.8050  2374.7800  ok  1588809600  17724705
19  2497.94  2500.0100  2353.2100  2361.0100  ok  1589414400  20568292
20  2410.39  2525.4500  2330.0000  2500.0000  ok  1590019200  16606580
21  2478.40  2488.0000  2378.2300  2384.3300  ok  1590624000  14861424
22  2647.45  2722.3500  2437.1300  2477.4300  ok  1591228800  20347790
23  2640.98  2671.3800  2503.3500  2603.5000  ok  1591833600  21664534
24  2734.40  2796.0000  2636.1100  2647.0100  ok  1592438400  20231829
25  2878.70  2895.0000  2630.0800  2739.5500  ok  1593043200  23825988
26  3081.11  3083.9700  2871.1021  2912.0100  ok  1593648000  23769178
27  3008.87  3344.2900  2950.0000  3115.9900  ok  1594252800  32615868
28  3099.91  3240.5758  2918.2300  2971.0600  ok  1594857600  28992931
29  3033.53  3098.2713  2888.0000  3098.2713  ok  1595462400  21560522
30  3205.03  3246.8200  3005.0000  3014.0000  ok  1596067200  27910616
31  3162.24  3247.4700  3073.0000  3194.3600  ok  1596672000  18289289
32  3260.48  3320.0000  3120.0000  3182.9900  ok  1597276800  18123114
33  3441.85  3451.7387  3238.0000  3252.0000  ok  1597881600  22076183
34  3531.45  3552.2500  3378.0000  3450.0500  ok  1598486400  18755541
35  3268.61  3488.4100  3111.1300  3485.0000  ok  1599091200  28225747
36  3078.10  3349.8900  3074.1500  3307.2188  ok  1599696000  23507043
37  2999.86  3133.9900  2871.0000  3009.2500  ok  1600300800  34061036
38  3148.73  3212.8800  2965.0000  2977.7900  ok  1600905600  22768258
39  3195.69  3224.0000  3090.0000  3208.0000  ok  1601510400  23756648
40  3363.71  3496.2400  3174.9900  3224.9900  ok  1602115200  28019796
41  3184.94  3399.6606  3160.0000  3292.0100  ok  1602720000  26023841
42  3162.78  3291.6600  3121.9400  3189.8700  ok  1603324800  23459220
43  3241.16  3257.2500  2950.1200  3201.2700  ok  1603929600  33986881
44  3137.39  3366.8000  3019.4828  3319.9700  ok  1604534400  28584900
45  3105.46  3189.2500  3072.6850  3159.9500  ok  1605139200  18304042
46  3185.07  3198.0000  3065.4600  3105.3100  ok  1605744000  18491800
47  3104.20  3228.6400  3088.0000  3205.4600  ok  1606953600  15944105
48  3240.96  3247.0000  3072.8200  3088.9900  ok  1607558400  18001977
49  3185.27  3263.5100  3166.0000  3250.0000  ok  1608163200  17782474
50  3285.85  3350.6500  3169.0000  3193.9000  ok  1608768000  15220947

In [7]:
from datetime import datetime
import requests
import pandas

stk_ticker = 'AMZN'
data_resolution = 'W'
timestamp_from = 1577865600
timestamp_to = 1609315200
API_Key = 'bsiqli7rh5rc8orbnkqg'
Address_template = 'https://finnhub.io/api/v1/stock/candle?symbol={}&resolution={}&from={}&to={}&token={}';

API_address = Address_template.format(stk_ticker,data_resolution,
                                      timestamp_from,timestamp_to,API_Key)

AMZN_df = pd.DataFrame(r.json())
AMZN_df.drop(columns=['s'],inplace=True)
AMZN_df.t = AMZN_df.t.apply(datetime.fromtimestamp)
AMZN_df.t = AMZN_df.t.apply(lambda v:v.date())
AMZN_df.set_index('t',drop=True,inplace=True)
AMZN_df.columns = ['Closing','High','Low','Opening','Volume']
AMZN_df.head()

            Closing     High      Low  Opening    Volume
t
2020-01-01  1891.97  1913.89  1860.00  1875.00  19514188
2020-01-08  1862.02  1917.82  1855.09  1909.89  15160738
2020-01-15  1887.46  1902.50  1857.25  1882.99  13580875
2020-01-22  1858.00  1894.99  1815.34  1885.11  14688733
2020-01-29  2039.87  2071.02  1850.61  1858.00  37459327